name: Build SWU

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        docker run --rm -e VERSION="${{ github.sha }}" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkjals/build /bin/bash -c "chmod +x /build/build-swu.sh && /build/build-swu.sh"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: update.swu
        path: |
          build/dist/update.swu
